sudo: false
language: python
python:
- "3.6"
before_install:
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz
  | tar -JxC $HOME/texlive
- pip install Pygments
script:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- pdflatex -shell-escape Concepts
- bibtex Concepts
- pdflatex -shell-escape Concepts
- pdflatex -shell-escape Concepts
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UjiTe2jeKb5r+FJ0qwtJ31Cp2lZdEpLv5j6S30BXoXqUTpLXdMfKpzlSuTIFED1uDFTJndrBBw8A6iQbF7V1tN0P0BKIhsBFyhEglaYCYYK2VA3hRUu8WDZxShCXc8Z1zfdZR441bIbITBTtjOj115h2eQtkOLZ0FmSMk3Jbr8rfClN8NsOKh7Y6cSvRg/M4uUdW5+A2iBgflYApiSLDG2tTFE9Q89isEMGJugaD27cO5GQsD7zIEvykRpHt0lBM2dVXcxB+lxQbrDGH4/IjQWx9VrmRR8bDnU3s5KPcHALZuzuPlSXDYD7zr7rLin0eT+C89mcLZogkYSAb8E448v1Xu3Nd63qWOsZkEL63ttSLaIBspA3ZOVQ4L+9J80ORS+4o51Q+kbTbfsQQCQyM+i0RkqkzjTewvJEZYGXmYM31eoFN7IXLrx6/BjdxwMDrTZt/7rfnbZ5rPLthgnLyix6qRxVlApCtKfsHcsIH6pSoxDHDzQjIsFzohUz1J8ce0xJtvzKHl/A52yjsr3UlIE85C4/vC+PLwSbRRLUqZCdAe3HPCJLEg5NedZpFmjaDjQZ3hjvrO7Pm+J/07AO9NkKuES03n9hGu6bvx4KMA1pbb0yY/qjHwKQCa5Ld0f2dEpCvW/QTHAOIlrCaHlCuGfZ9Rex3yGWDLLQmZB/7LeA=
  file: Concepts.pdf
  on:
    repo: jrbeaumont/concepts-tool-paper
